config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/show'

  get 'users/edit'

  get 'users/update'

  get 'users/new'

  devise_for :users
  get 'about/index'
  get 'about/show'
  get 'about' => 'about#index'

  get 'songs/show'

  get 'songs/current'

  get 'home/index'

  get 'pictures/approve' => 'pictures#approve'
  get 'pictures/last_approve' => 'pictures#get_last_approve', as: 'get_last_approve'

  post 'pictures/approveThePic/:id' => 'pictures#approveThePic', as: 'approve_the_pic_post'
  get 'pictures/approveThePic/:id' => 'pictures#approveThePic', as: 'approve_the_pic_get'

  get 'pictures/approve/:id' => 'pictures#approve', as: 'pic_approve'
  root 'home#index'

  resources :songs
  resources :pictures

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	# attr_accessor :title, :approved this messed everything up!!
	# attr_accessor :approved
	
	# after initialize is for whenever its loaded form db or instantiated
	# after_initialize :defaults
	after_create :defaults

	has_attached_file :image
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	

	def defaults
		self.approved = false
	end

	def approvePicture
		self.approved=false
	end 

	def approvePictureTrue
		self.approved=true
	end


	def getSrc
		if self.vibeType == "soundcloud" or self.vibeType == "2"
			source ="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/"
			source += self.uid
			source += "&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"
		else self.vibeType == "youtube" or self.vibeType == "3"
			source ="https://www.youtube.com/embed/"
			source += self.uid if self.uid
		end	
	end

	def getSrcSoundcloud
		source ="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/"
		source += self.uid
		source += "&amp;auto_play=true&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"
	end

	def getNextSongId
		this_id = self.id
		for eachItem in this_id+1..Picture.last.id
				thisPic = Picture.where(id: eachItem)
				if thisPic.vibeType == 'soundcloud'
					thisPic.id
				else
					next
				end
		end
		false
	end




end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/song.rb
class Song < ActiveRecord::Base

	def get_src
		b= url.index('src=')
		e = url.index('></')
		src = url[b+5..e-2]
	end

end


# begin = @song.url.index('src=')
# end = @song.url.index('></')

# src=@song.url[begin+5..end-2]

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  	
  end

  def show
	send_file(Rails.root.join("app", "assets", "images", "PLResume.PDF").to_s, :disposition => "inline", :type => "application/pdf")
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@pictures = Picture.paginate(:page => params[:page], :per_page => 20)
  	# @pictures=@pictures.reverse

    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    redirect_to root_path
    @pictures = Picture.all.reverse
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end


  # This was my first ever rails application, and I modified the "Pictures" model to encompass all types of media. 
  # Rather than having 3 separate models for Pictures, Songs, or Videos, I have one Pictures model where you can choose 
  # the "Type" of media it is. 

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    if @picture.vibeType == "soundcloud" or @picture.vibeType == "2" 
        start= 'content="soundcloud://sounds:'
        i = open(@picture.url).read.index(start)
        @picture.uid = open(@picture.url).read[i+29..i+37] 
    elsif @picture.vibeType == "image" or @picture.vibeType == "1" 
      @picture.uid = @picture.url
    elsif @picture.vibeType == "youtube" or @picture.vibeType == "3" 
      start = 'watch'
      i = @picture.url.index(start)
      pp = @picture.url[i, i+1]
      @picture.uid = pp[8,100]
    end

    respond_to do |format|
      if @picture.save
        format.html { redirect_to root_path, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to root_path, notice: 'Picture Deleted'
  end

  def approve
    # TODO select pictures that are approved
    # Picture.update_all(['approved=?', true], :id => params[:picture_ids])
    @picture=Picture.find(params[:id])
    @picture.approvePicture
    # @picture.approved=true
    # redirect_to pictures_path    
  end

  def approveThePic 
    @picture=Picture.find(params[:id])
    @picture.approvePictureTrue
    @picture.save
    redirect_to pictures_path   
  end

  def get_last_approve
    @picture=Picture.last 
    redirect_to pic_approve_path(@picture)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:title, :image, :approved, :vibeType, :body, :url, :uid)

    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  
  # This was my first ever rails application, and I modified the "Pictures" model to encompass all types of media. 
  # Rather than having 3 separate models for Pictures, Songs, or Videos, I have one Pictures model where you can choose 
  # the "Type" of media it is. 

  def index
    @song = Picture.where(vibeType: ["2", "soundcloud"])
    # pry
  end

  def show
    @song = Picture.find(params[:id])
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)
 
    if @song.update(song_params)
      redirect_to @song
    else
      render :new
    end
  end

  def update
    @song = Song.find(params[:id])

    if @song.update(song_params)
      redirect_to @song
    else
      render :new
    end
  end

  def edit
    @song = Song.find(params[:id])
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    redirect_to root_path, notice: 'Song Deleted'
  end

private

  def song_params
    params.require(:song).permit(:url, :type)
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def new
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<!-- About Page -->
<head>
<style>
	.background_image {
		/*border-bottom: solid;*/
		border-width: 3px;
		/*padding-bottom: 1px;*/
	}

	body {
		background: url('/assets/icelandbeach.jpg');
		background-attachment: fixed;
	}

</style>
</head>

<body>

</br>

<link href='http://fonts.googleapis.com/css?family=Megrim' rel='stylesheet' type='text/css'>
<h1>phillip lisovicz</h1>
<hr>

<p class="about-wrapper"> 
good || vibes || only
</br></br>
<span class="signature">  made with rails  </span>

</br></br>
DevOps @eXelate

</br>
<span class="signature"> phillip.lisovicz@gmail.com </span>
</br>
</p>


</br>
</br>
</body>
</html>

app/views/about/show.html.erb
<!DOCTYPE html>
<html>
<body>

<h1>phil lisovicz</h1>

<div class="background_image">
    <img src="http://s3.amazonaws.com/phillslife-assets/pictures/images/000/000/002/original/Nantucket_Pan.JPG?1417479373" alt="Nantucket" style="width:100%;height:400px;">
</div>

<p> 


</p>
</body>
</html>

app/views/home/_pictures.html.erb
<!-- Rendered template for the pictures/videos/songs -->
<script>
$(document).ready(function() {
    var $container = $('#picture-container');
	$container.isotope({ itemSelector: '.fancybox', sortBy: 'original-order' })    
    $container.imagesLoaded( function() {
        // alert("images are loaded");
        setTimeout(1000);
	    $container.masonry({
		    // options
		  	itemSelector: '.fancybox',
	    	columnWidth: 320
		});
		$('.fancybox').show(); 
		// $container.isotope({ sortBy: 'original-order' });	    
    });
})
</script>

<% @pictures.each do |pic| %>
    <% if pic.approved==true %>
	    <% if pic.vibeType == "2" or pic.vibeType == "soundcloud" %>
	        <div class="fancybox"> 
	            <iframe width="320" height="250" scrolling="no" frameborder="no" src="<%= pic.getSrc.to_s %>" ></iframe> 
	            <p class="sort_by_value" style="display:none;"> <%= pic.created_at %></p>
	        </div>
	    <% elsif pic.vibeType == "3" or pic.vibeType == "youtube" %>
	        <div class="fancybox"> 
	            <iframe width="320" height="250" frameborder="0"src="<%= pic.getSrc.to_s %>" > </iframe> 
	            <p class="sort_by_value" style="display:none;"> <%= pic.created_at %></p>
	        </div>
	    <% else %>
	        <div class="fancybox">

	            <%= link_to (image_tag pic.image.url), picture_path(pic) %>
	            <p class="sort_by_value" style="display:none;"> <%= pic.created_at %></p>

	        </div>
	    <% end %>
	<% end %>
<% end %>

app/views/home/index.html.erb
<!-- Main page: Uses masonry to dynamically layout the images/videos/songs -->

<head>
	<script src="http://cdnjs.cloudflare.com/ajax/libs/masonry/3.3.0/masonry.pkgd.js"></script>
	<script src="http://imagesloaded.desandro.com/imagesloaded.pkgd.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.2.2/isotope.pkgd.js"></script>
    <style>

    .fancybox {
    	display:none;
    }

    h1 {
	    color: #365ebf;
    }
    </style>
</head>

<body> 
</br>

<h1 id="title" style="color:"> phill's life </h1>
<h2><%= link_to 'upload', new_picture_path %></h2>

<div id="container-fluid">

	<!-- Use rails gem will_paginate to implemenet pagination / infinite scroll -->
	<!-- Rendering the _pictures.html.erb template -->
	<div id="pictures">
		<div id="picture-container" data-masonry-options='{ "itemSelector": ".fancybox", "columnWidth": 320 }'>
			  <%= render 'pictures' %>
		</div>
	</div>
<%= will_paginate @pictures %>

</div>
<!-- Masonry Layout -->
<script>
	$(document).ready(function() {
	    var $container = $('#picture-container');
	    $container.imagesLoaded( function() {
	    	$container.isotope({ itemSelector: '.fancybox', sortBy: 'original-order' })
		    $container.masonry({
			    // options
			  	itemSelector: '.fancybox',
		    	columnWidth: 320

			});
			$container.isotope({
				// options...
				itemSelector: '.fancybox',
				sortBy: 'original-order',
				masonry: {
					columnWidth: 320
				}
			});
		});
	});

</script>

</body>

app/views/home/index.js.erb
// Implementing infinite scrolling and calling masonry again on the newly added pictures.

$(document).ready(function() {
	$('#pictures').append("<%= escape_javascript render 'pictures' %>");
	$('.pagination').replaceWith("<%= escape_javascript will_paginate @pictures %>");

    var $container = $('#pictures');   
    $container.imagesLoaded( function() {
    	$container.isotope({ itemSelector: '.fancybox', sortBy: 'original-order' })	
        $container.masonry({
            itemSelector: '.fancybox',
	    	columnWidth: 320    
        });
		$container.isotope({
			// options...
			itemSelector: '.fancybox',
			sortBy: 'original-order',
			masonry: {
				columnWidth: 320
			}
		});
        $container.masonry('reloadItems');
    });
})

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>phills life</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href='http://fonts.googleapis.com/css?family=Bad+Script|Englebert|Delius|Loved+by+the+King|Over+the+Rainbow' rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href="/assets/faviconPL.ico" type="image/x-icon" />
  <!-- // <script src="assets/isotope.pkgd.min.js"></script> -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.2.2/isotope.pkgd.js"></script>


<!-- Bootstrap Latest compiled and minified CSSand JS -->
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script> -->

</head>
<body>

<link href='http://fonts.googleapis.com/css?family=Megrim' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>

<!-- Application default page - Navbar -->
  <div class="nav">
    <ul>
      <li id="words"><%= link_to 'home', root_path %></li>
      <li id="words"><%= link_to 'music', songs_path %></li> 
      <li id="words"><%= link_to 'about', about_path %></li> 
      <li id="logo"><iframe allowtransparency="true" scrolling="no" frameborder="no" src="https://w.soundcloud.com/icon/?url=http%3A%2F%2Fsoundcloud.com%2Fphillslife&color=orange_transparent" style="width:60px;height:38px; text-align: center;padding-top:0;"></iframe> </li>
      <% if user_signed_in? %>
        <li id="words-right"> <%= link_to 'sign out', destroy_user_session_path, method: :delete,  :confirm => 'Are you sure?'%> </li>
      <% else %>
        <!-- <li id="words-right"> <%= link_to 'sign in', new_user_session_path %> </li> -->
      <% end %>
    </ul>
  </div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<!-- Yield the rest of the application -->
<%= yield %>

</body>
</html>

app/views/pictures/approve.html.erb
<head>

<style>

body {
	/*background: url('/assets/colorado.jpg');*/
    background-color: #365ebf;
	background-attachment: fixed;
}

</style>

</head>

<body>
<br>

<!-- If a random visitor uploads a picture, I need to be able to approve it before I want it on my site. This is kind of hacked together -->
<!-- to assume that the visitor is not malicious, and won't go around looking for how to approve uploaded content -->
<div class="pic-container">
	<div class="pic-show-container-test">

		<!-- soundcloud -->
		<% if @picture.vibeType=="2" or @picture.vibeType == "soundcloud"  %>
            <div class="pic"> 
                <iframe width="50%" height="350" frameborder="0"src="<%= @picture.getSrc.to_s %>" > </iframe> 
            </div>
			<div class="approve-box">
				<form action=<%= approve_the_pic_post_path(@picture) %> method="post">
					<input type="submit" value="approve"></input></br>
					<th><%= link_to 'delete', picture_path(@picture, :id => @picture.id), method: :delete %> </th>
				</form>
			</div>

		<!-- youtube -->
		<% elsif @picture.vibeType=="3" or @picture.vibeType == "youtube" %>
            <div class="pic"> 
                <iframe width="50%" height="350" frameborder="0"src="<%= @picture.getSrc.to_s %>" allowfullscreen> </iframe> 
            </div>
			<div class="approve-box">
				<form action=<%= approve_the_pic_post_path(@picture) %> method="post">
					<input type="submit" value="approve"></input></br>
					<th><%= link_to 'delete', picture_path(@picture, :id => @picture.id), method: :delete %> </th>
				</form>
			</div>

		<!-- pictures -->
		<% else %>
			<div class="pic">
				<%= image_tag @picture.image.url, style: "width:50%; height:350;" %>
			</div>
			<div class="approve-box">
				<form action=<%= approve_the_pic_post_path(@picture) %> method="post">
					<input type="submit" value="approve"></input></br>
					<th><%= link_to 'delete', picture_path(@picture, :id => @picture.id), method: :delete %> </th>
				</form>
			</div>
		<% end %>
	</div>
</div>


</body>

app/views/pictures/edit.html.erb
<%= render 'form' %>

app/views/pictures/new.html.erb
<%= render 'form' %>

app/views/pictures/show.html.erb
<head>

<style>

body {
    background-color: #365ebf;
    /*background: url('/assets/colorado.jpg');*/
    background-attachment: fixed;
}

#some_link a {
    color: #365ebf;
}

</style>
</head>

<body>

<br>

<div id="some_link" style="text-align:center;color:#365ebf;margin-bottom:2em;">
    <%= link_to 'last approved..', get_last_approve_path(@picture) %>
</div>

<div class="pic-container">
	<div class="pic-show-container-test">
            <% if @picture.approved==true %>
                <% if @picture.vibeType == "2" %>
                    <div class="pic"> 
                        <iframe width="50%" height="350" scrolling="no" frameborder="no" src="<%= @picture.getSrc.to_s %>" ></iframe> 
                    </div>
                <% elsif @picture.vibeType == "3" %>
                    <div class="pic"> 
                        <iframe width="50%" height="350" frameborder="0"src="<%= @picture.getSrc.to_s %>" allowfullscreen> </iframe> 
                    </div>
                <% else %>
                    <a class="pic" href=<%= "#{@picture.image.url}" %> data-lightbox="#{@picture.id}">
                        <%= image_tag @picture.image.url, style: "width:50%; height:auto;" %>
                    </a>
                <% end %>
            <% end %>
<!--             <div class="approve-box">
                <%= simple_form_for(@picture) do |f| %>
                    <table>
                        <tr>
                            <th> <%= link_to image_tag("glyphicons-173-rewind.png"), picture_path(@picture.id - 1), style: "width:10; height: 2em;"%> </th>
                            <th> </th>
                            <th> <%= link_to image_tag("glyphicons-177-forward.png"), picture_path(@picture.id + 1)%> </th>
                        </tr>
                    </table>
                <% end %>
            </div> -->
	</div>
</div>


</body>

app/views/songs/_form.html.erb
<style>

form {
	text-align: center;
}


</style>

<body> 

<div id="wrapper">

<h1> phills life </h1>


<div class="background_image">
    <img src="/assets/Nantucket_Pan.JPG" alt="Nantucket" style="width:100%;height:400px;">
</div>



<div class="firstPost">

	<div class="my-form">
	  <%= form_for(@song) do |f| %>

	  	<%= f.text_field :url %>

      <div class="actions">
        <%= f.submit "submit" %>
      </div>

	  <% end %>
	</div>

</div>

<!-- disabling upload for now -->




</br>

</br>

</br>

</br>

</br>

</br>
</div>

app/views/songs/current.html.erb
	<!DOCTYPE html>
<html>

<head>


<style>

.background_image {
	/*border-bottom: solid;*/
	border-width: 3px;
	/*padding-bottom: 1px;*/
}

body {
	background: url('/assets/colorado.jpg');
	background-attachment: fixed;
}

</style>


</head>

<body>



<div class="background_image">
    <!-- <img src="/assets/Nantucket_Pan.JPG" alt="Nantucket" style="width:100%;height:400px;"> -->
</div>
<br>


<!-- 
<h2 class="h3link"><%= link_to 'all timers', songs_path %>
	<% if user_signed_in? %>
		&nbsp | &nbsp <%= link_to 'new song', new_song_path %>
	<% end %>
</h2> -->


<div class="songs-wrapper">
	<!-- <h1 id="currentSongH1"> current </h1> -->
	<p>currently enjoyable tunes</p>

	<div class="posts">
		<iframe scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/180553086&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
	</div>

	<div class="posts">
		<iframe scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/184628453&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
	</div>

	<div class="posts">
		<iframe src="https://embed.spotify.com/?uri=spotify:track:0ZtLv7aVallYjnPJNZJWk7" scrolling="no" frameborder="no" allowtransparency="true"></iframe>
	</div>

	<div class="posts">
		<iframe scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/173290651&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
	</div>

	<div class="posts">
		<iframe scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/177352611&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
	</div>

	<div class="posts">
		<iframe scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/178476348&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
	</div>

	<div class="posts">
		<iframe scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/176315030&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
	</div>

	<div class="posts">
		<iframe scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/170202151&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
	</div>

	<br>


</div>

<br>



<br>


</br>
</br>
</br>

</body>
</html>

app/views/songs/index.html.erb
<head>
<style>

	body {
		background: url('/assets/icelandbeach.jpg');
		background-size: 100%;
		background-attachment: fixed;
	}

</style>
</head>

<body>

<br>
<link href='http://fonts.googleapis.com/css?family=Megrim' rel='stylesheet' type='text/css'>

<h1> vibes </h1>
<hr>

<div class="about-wrapper">
	<table>
		<tr id="table-header">
			<th> track </th>
			<th> artist </th>
			<th> vibe </th>
		</tr>
		<% @song.reverse.each do |song| %>
			<% if song.approved %>
				<div class="item">
						<tr>
							<th> <span class="signature"> <%= song.title %> </span> </th>
							<th> <%= song.body %>  </th>
							<th> <%= link_to image_tag("glyphicons-77-headphones.png"), song_path(song) %> </th>
						</tr>
				</div>
			<% end %>
		<% end %>
	</table>
</div>

</body>
</html>

app/views/songs/show.html.erb
<head>

<style>
    body {
    	background: url('/assets/colorado.jpg');
    	/*background: url('/assets/nice.jpg');*/
    	background-attachment: fixed;
    }

    #sign img {
        height: 50px;
        display: inline;
        position: relative;
    }

    #comment tr{
        vertical-align: text-top;
    }

    #small-font {
        font-size: 12px;
    }
</style>
</head>

<body>
<br>

<!-- new -->
<div class="pic-container">
    <div class="pic-show-container-test">
        <% if @song.vibeType=="2" or song.vibeType=="soundcloud"%>
            <div class="pic"> 
                <iframe width="50%" height="350" scrolling="no" frameborder="no" src="<%= @song.getSrcSoundcloud.to_s %>" >
                </iframe> 
            </div>
            <div class="approve-box">
                <div id="small-font"> <%= link_to 'back to songs', songs_path %> </div>
            </div>
        <% end %>
    </div>
</div> 
<!-- end new -->



<!-- orig -->
<!-- <div class="pic-container">
	<div class="pic-show-container-test">
		<% if @song.vibeType=="2" %>
			<div class="pic"> 
                <iframe width="50%" height="350" scrolling="no" frameborder="no" src="<%= @song.getSrcSoundcloud.to_s %>" >
                </iframe> 
            </div>
            <div class="approve-box">
                <table>
                    <tr>
                        <% if (@song.id - 1) == true %>
                            <th><div id="sign"> <%= link_to image_tag("lessthan.png"), songs_show_path(@song.id - 1) %> </div> </th>
                        <% else %>
                             <th><div id="sign"> <%= link_to image_tag("lessthan.png"), songs_path %> </div> </th>              
                        <% end %>
                        <% if (@song.id + 1) == true %>
                            <th><div id="sign"> <%= link_to image_tag("greaterthan.png"), songs_show_path(@song.id + 1) %> </div> </th>
                        <% else %>
                             <th><div id="sign"> <%= link_to image_tag("greaterthan.png"), songs_path %> </div> </th>              
                        <% end %>
                    </tr>
                    <tr id="comment">
                        <% if (@song.id - 1) == true %>
                            <th> prev </th>
                        <% else %>
                             <th> songs </th>              
                        <% end %>
                        <% if (@song.id + 1) == true %>
                            <th> next </th>
                        <% else %>
                             <th> songs </th>              
                        <% end %>
                    </tr>
                	<% link_to image_tag("glyphicons-225-chevron-left.png"), songs_path %>
                </table>
            </div>

        <% end %>
    </div>
</div> -->
<!-- end orig -->






</body>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<%= render 'form' %>